### ISSUE TITLE
增加一些设置方面的东西

### ISSUE THREAD

**Issue by lh5210069** [tiddly-gittly/tiddlywiki-calendar#20]
1、可以给设置界面增加一个是否显示modified条目的选项，这样方便平时查看主动添加的一些条目，界面也更清爽一些，如果碰到修改的条目比较多的话就显得很凌乱，查看修改过的条目的需求并不高，所以是不是考虑加一个。
2、手机layout界面没有month视图，只有三天的是不是可以考虑加一个。
3、layout界面添加条目时出现常用的tag选择做成下拉列表，界面会不会更清爽一些。

**Comment by linonetwo** [comment]
设置是直接跳转还是先打开小窗

**Comment by linonetwo** [comment]
你常用tag很多吗，截图看看？

**Comment by lh5210069** [comment]
常用的不多，做成下拉选择，而且下拉也可以做成层级那种，筛选添加那个就放在下拉旁边，我的意思是这样在手机界面比较小的情况下会相对比较简洁一些，输入文本框大小是不是考虑缩小一些，一般情况下文本框用的频率小于CAPTION，这样总体下来会绝的舒服一些，个人感受。
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: lin ***@***.***>
发送时间: 2023年1月30日 10:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [tiddly-gittly/tiddlywiki-calendar] 增加一些设置方面的东西 (Issue #20)


你常用tag很多吗，截图看看？

―

**Comment by linonetwo** [comment]
不多应该就不用做成下拉选择了吧

**Comment by linonetwo** [comment]
有兴趣可以PR改看看，附上截图
